- name: Install basic shell utilities (Debian derivatives)
  apt:
    state: present
    name:
      - curl
      - emacs
      - git
      - htop
      - inotify-tools
      - jq
      - mosh
      - progress
      - silversearcher-ag
      - tmux
      - vim
      - zsh

- include: common.yml
