- name: Install basic shell utilities (All platforms)
  package:
    state: present
    name: 
      - curl
      - emacs
      - git
      - htop
      - inotify-tools
      - jq
      - mosh
      - progress
      - tmux
      - vim
      - zsh

- include_vars:
    file: "{{ item }}"
    name: platform_specific
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install basic shell utilities (Platform specific names)
  package:
    name: "{{ platform_specific.packages }}"
    state: present

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
  become_user: "{{ user }}"

- name: Install oh-my-zsh nix shell plugin
  git:
    repo: https://github.com/chisui/zsh-nix-shell.git
    dest: ~/.oh-my-zsh/custom/plugins/nix-shell
  become_user: "{{ user }}"

- name: Install oh-my-zsh nix completions plugin
  git:
    repo: https://github.com/spwhitt/nix-zsh-completions.git
    dest: ~/.oh-my-zsh/custom/plugins/nix-zsh-completions
  become_user: "{{ user }}"

- name: Change shell to zsh
  user:
    name: "{{ user }}"
    shell: /bin/zsh
