---
- name: Upgrade all servers
  hosts: servers

  tasks:
    - name: Upgrade apt
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
      when: ansible_distribution == "Ubuntu"
  
    - name: Upgrade yum
      debug: msg="No configuration available for Fedora based distros."
      when: ansible_distribution == "Fedora"