- hosts: localhost
  roles:
    - role: personal-dotfiles
      tags: [shell, ui, personal, dotfiles]
    - role: shell-basics
      tags: [shell, shell-basics]
    - role: ui-basics
      tags: [ui, ui-basics]
    - role: ui-workstation
      tags: [ui, workstation]
    - role: devtools-vscode
      tags: [ui, devtools, vscode]
    - role: devtools-neovim
      tags: [shell, devtools, neovim]
    - role: devtools-emacs
      tags: [shell, devtools, emacs]
    - role: utils-docker
      tags: [utils, docker]
    - role: utils-virtualization
      tags: [utils, virtualization]
    - role: dev-javascript
      tags: [dev, javascript]
    - role: dev-elixir
      tags: [dev, elixir]
    - role: dev-elm
      tags: [dev, elm]
    - role: dev-openjdk8
      tags: [dev, openjdk8]
