- hosts: localhost
  roles:
    - role: personal-dotfiles
      tags: [shell, ui, personal, dotfiles]
    - role: shell-basics
      tags: [shell, shell-basics]
    - role: devtools-neovim
      tags: [shell, devtools, neovim]
    - role: utils-docker
      tags: [utils, docker]
    - role: service-portainer
      tags: [northrend, portainer]
    - role: dev-python
      tags: [dev, python]
    - role: dev-javascript
      tags: [dev, javascript]
    - role: dev-elixir
      tags: [dev, elixir]
    - role: server-basics
      tags: [server, northrend]
    - role: server-nginx
      tags: [server, nginx, northrend]
    - role: server-certbot
      tags: [server, certbot, northrend]
    - role: server-mariadb
      tags: [server, mariadb, northrend]
    - role: server-php
      tags: [server, php, northrend]
    - role: dev-openjdk8
      tags: [dev, openjdk8]
#    - role: service-sbsk-tools
#      tags: [northrend, service-sbsk-tools]

