- hosts: localhost
  roles:
    - role: utils-shell
      tags: utils-shell
    - role: utils-neovim
      tags: utils-neovim
    - role: utils-gui
      tags: utils-gui
    - role: utils-virtualization
      tags: utils-virtualization
    - role: utils-docker
      tags: utils-docker
    - role: dev-python
      tags: dev-python
    - role: dev-javascript
      tags: dev-javascript

