- hosts: localhost
  roles:
    - role: personal-dotfiles
      tags: [shell, ui, personal, dotfiles]
    - role: shell-basics
      tags: [shell, shell-basics]
    - role: devtools-emacs
      tags: [shell, devtools, emacs]
    - role: utils-docker
      tags: [utils, docker]
    - role: dev-python
      tags: [dev, python]
    - role: dev-javascript
      tags: [dev, javascript]
    - role: dev-elixir
      tags: [dev, elixir]
    - role: server-basics
      tags: [server, northrend]

