- name: Add Node repository
  yum_repository:
    name: nodesource
    description: Nodesource Repository
    baseurl: https://rpm.nodesource.com/pub_12.x/fc/$releasever/$basearch
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    gpgcheck: yes

- name: Install nodejs tools
  dnf: name=nodejs state=present

- name: Create user global NPM folder
  file:
    path: ~/.npm-packages/
    state: directory
  become_user: "{{ user }}"
