- name: Add Node repository
  yum_repository:
    name: nodesource
    description: Nodesource Repository
    baseurl: https://rpm.nodesource.com/pub_8.x/fc/$releasever/$basearch
    gpgkey: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    gpgcheck: yes

- command: dnf makecache

- name: Install nodejs tools
  dnf: name=nodejs state=present
