- name: Install WeeChat repository signing key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E

- name: Add WeeChat repositories
  apt_repository: repo='deb https://weechat.org/ubuntu xenial main'

- name: Install WeeChat
  apt: pkg=weechat state=latest

- name: Install oidentd
  apt: pkg=oidentd state=latest

- name: Install oidentd configuration
  template: src=oidentd.conf.j2 dest=/etc/oidentd.conf owner=root group=root mode=0644