- name: Add Virtualbox repository (yum)
  yum_repository:
    name: virtualbox
    description: Virtualbox Repository
    baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch/
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    gpgcheck: yes
    repo_gpgcheck: yes
  when: ansible_distribution == "Fedora"

- name: Install virtualization tools (dnf)
  dnf: name={{ item }} state=present
  with_items:
    - VirtualBox-5.0
    - vagrant
  when: ansible_distribution == "Fedora"