- name: Add neovim repository
  yum_repository:
    name: neovim
    description: Neovim repository - owned by dperson
    baseurl: https://copr-be.cloud.fedoraproject.org/results/dperson/neovim/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/dperson/neovim/pubkey.gpg
    skip_if_unavailable: yes
    gpgcheck: yes

- name: Install Neovim (Fedora)
  dnf: name={{ item }} state=present
  with_items:
    - neovim
    - python-neovim

- name: Install dein plugin manager
  shell: curl -s -L https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s "{{ user_home}}/.config/nvim/dein"
  become_user: "{{ user }}"

- name: Configure neovim alternatives
  alternatives: name="{{ item }}" link=/usr/local/bin/{{ item }} path=/usr/bin/nvim
  with_items: 
    - vi
    - vim
    - editor

- name: Link neovim config
  file:
    src: "{{ role_path }}/files/nvim"
    dest: "~/.config/nvim"
    state: link
  become_user: "{{ user }}"

- name: Install neovim dein plugins
  command: nvim +"call dein#update()" +"qall" --headless
  become_user: "{{ user }}"
