- name: Add Sway repository
  yum_repository:
    name: gumieri-sway
    description: Copr repo for sway owned by gumieri
    baseurl: https://copr-be.cloud.fedoraproject.org/results/gumieri/sway/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/gumieri/sway/pubkey.gpg
    gpgcheck: yes

- name: Install sway related packages
  dnf:
    state: present
    name:
      - sway
      - light
      - mako
      - grim
      - slurp
      # Below: Not sway related, but useful apps nontheless
      - pavucontrol
      - NetworkManager-tui
      - mirage # Image viewer

- git:
    repo: https://github.com/tobi-wan-kenobi/bumblebee-status.git
    dest: ~/bin/apps/bumblebee-status
    version: master
  become_user: "{{ user }}"
