version: '3'
services:
  factorio:
    image: dtandersen/factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - "{{ factorio.root_folder}}/data:/factorio"
    networks:
      - bridge

networks:
  bridge:
    external: true
