- name: Create folder to store traefik configuration
  become: yes
  file:
    path: /opt/traefik/
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy traefik configuration files
  become: yes
  template:
    src: "{{ item }}"
    dest: /opt/traefik/{{ item }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - traefik.toml

- name: Ensure acme storage file exists
  become: yes
  file:
    path: /opt/traefik/acme.json
    state: touch
    owner: root
    group: root
    mode: 0600

- name: Ensure traefik external network exists
  become: yes
  docker_network:
    name: traefik-external
    internal: no

- name: Deploy traefik container
  become: yes
  docker_compose:
    project_name: traefik
    definition:
      version: "2"
      services:
        traefik:
          image: traefik:1.7
          restart: always
          ports:
            - "80:80"
            - "443:443"
            - "127.0.0.1:11000:11000"
          networks:
            - traefik-external
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/traefik/traefik.toml:/traefik.toml
            - /opt/traefik/acme.json:/acme.json
      networks:
        traefik-external:
          external: yes

