- name: Deploy miniflux
  become: yes
  docker_compose:
    project_name: miniflux
    definition:
      version: '3'
      services:
        miniflux:
          image: miniflux/miniflux:latest
          depends_on:
            - db
          networks:
            - miniflux
            - traefik-external
          environment:
            - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
            - RUN_MIGRATIONS=1
            - PORT=8080
            - BASE_URL=https://apps.bitnexus.net/miniflux/
          labels:
            - "traefik.backend=miniflux-backend"
            - "traefik.docker.network=traefik-external"
            - "traefik.frontend.rule=Host:apps.bitnexus.net;PathPrefix:/miniflux"
            - "traefik.frontend.redirect.regex=^(.*)/miniflux$$"
            - "traefik.frontend.redirect.replacement=$$1/miniflux/"
            - "traefik.enable=true"
            - "traefik.port=8080"
        db:
          image: postgres:latest
          environment:
            - POSTGRES_USER=miniflux
            - POSTGRES_PASSWORD=secret
          volumes:
            - miniflux-db:/var/lib/postgresql/data
          networks:
            - miniflux
      volumes:
        miniflux-db:
      networks:
        miniflux:
        traefik-external:
          external: yes

- name: Information about user setup for miniflux
  debug:
    msg:
      - "If this is the first time you setup miniflux, remember to create a user. Howto:"
      - "docker exec -it <container> /usr/bin/miniflux -create-admin"
