- name: Create required paths
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/
    - ~/.config/Code/
    - ~/.config/fontconfig/conf.d/
    - ~/.config/rofi/
    - ~/.config/terminator/
    - ~/.local/share/applications/
  become_user: "{{ user }}"

- name: Install dotfiles
  file:
    src: "{{ role_path }}/files/dotfiles/{{ item }}"
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .config/albert.conf
    - .config/Code/User
    - .config/fontconfig/conf.d/50-no-embedded.conf # ensures embedded bitmaps are not used for fonts. Fixes ligature bugs in calibri etc.
    - .config/rofi/config
    - .config/rofi/theme-dag.rasi
    - .config/terminator/config
    - .config/sway/config
    - .emacs.d
    - .gitconfig
    - .local/share/applications/emacs.desktop
    - .profile
    - .tmux.conf
    - .vimrc
    - .zshrc
  become_user: "{{ user }}"
