- name: Create required paths
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/fontconfig/conf.d/
    - ~/.config/Code
  become_user: "{{ user }}"

- name: Install dotfiles
  file:
    src: "{{ role_path }}/files/dotfiles/{{ item }}"
    dest: ~/{{ item }}
    state: link
    force: yes
  with_items:
    - .emacs.d
    - .gitconfig
    - .vimrc
    - .profile
    - .tmux.conf
    - .zshrc
    - .config/fontconfig/conf.d/50-no-embedded.conf # ensures embedded bitmaps are not used for fonts. Fixes ligature bugs in calibri etc.
    - .config/Code/User
  become_user: "{{ user }}"
