- name: Create neovim config directory if required
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.config/nvim
  become_user: "{{ user }}"

- name: Link neovim init-file to .vimrc
  file:
    src: ~/.vimrc
    dest: "~/.config/nvim/init.vim"
    state: link
    force: yes
  become_user: "{{ user }}"

- name: Configure neovim alternatives
  alternatives: name="{{ item }}" link=/usr/local/bin/{{ item }} path=/usr/bin/nvim
  with_items: 
    - vi
    - vim
