- name: Set up concourse CI server
  become: yes
  docker_compose:
    project_name: concourse
    definition:
      version: '2'
      services:
        concourse-db:
          image: postgres
          restart: always
          environment:
            - POSTGRES_DB=concourse
            - POSTGRES_PASSWORD=klnsfjklsdfklsdklsdf
            - POSTGRES_USER=concourse_user
            - PGDATA=/database
          networks:
            - concourse
          volumes:
            - pgdata:/var/lib/postgresql/data
        concourse:
          image: concourse/concourse:7.5.0
          restart: always
          command: quickstart
          privileged: true
          depends_on: 
            - concourse-db
          networks:
            - traefik-external
            - concourse
          environment:
            - "CONCOURSE_POSTGRES_HOST=concourse-db"
            - "CONCOURSE_POSTGRES_USER=concourse_user"
            - "CONCOURSE_POSTGRES_PASSWORD=klnsfjklsdfklsdklsdf"
            - "CONCOURSE_POSTGRES_DATABASE=concourse"
            - "CONCOURSE_EXTERNAL_URL=https://concourse.bitnexus.net"
            - "CONCOURSE_ADD_LOCAL_USER=dagolap:$$2b$$12$$dzCk1D5ZTLPhcMF8MoU9.Or.ZZIEdPNewE94xogjzOe/cMHPysQ82"
            - "CONCOURSE_MAIN_TEAM_LOCAL_USER=dagolap"
          labels:
            - "traefik.backend=concourse-backend"
            - "traefik.docker.network=traefik-external"
            - "traefik.frontend.rule=Host:concourse.bitnexus.net"
            - "traefik.enable=true"
            - "traefik.port=8080"
      networks:
        concourse:
        traefik-external:
          external: yes
      volumes:
        pgdata:
