- name: Create git group
  become: yes
  group:
    name: git
    gid: 10001
    state: present

- name: Create git user
  become: yes
  user:
    name: git
    comment: Gitea Git
    uid: 10001
    group: git

- name: Create folder to store gitea configuration
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    mode: 0700
  with_items:
    - /opt/gitea/
    - /opt/gitea/data/

- name: Deploy gitea
  become: yes
  docker_compose:
    project_name: gitea
    definition:
      version: "2"
      services:
        web:
          image: gitea/gitea:1.11.1
          restart: always
          volumes:
            - /opt/gitea/data:/data
          networks:
            - traefik-external
          ports:
            - "22000:22000"
          environment:
            - USER_UID=10001
            - USER_GID=10001
          labels:
            - "traefik.backend=gitea-backend"
            - "traefik.docker.network=traefik-internal"
            - "traefik.frontend.rule=Host:gitea.bitnexus.net"
            - "traefik.enable=true"
            - "traefik.port=3000"
      networks:
        traefik-external:
          external: yes

