- name: Create folder to store gitea configuration
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - /opt/gitea/
    - /opt/gitea/data/

- name: Copy gitea configuration files
  become: yes
  template:
    src: docker-compose.yml
    dest: /opt/gitea/docker-compose.yml
    owner: root
    group: root
    mode: 0600

- name: Redeploy gitea container - will pull and restart if necessary
  become: yes
  command: docker stack deploy --prune -c /opt/gitea/docker-compose.yml gitea
  args:
    chdir: /opt/gitea
