#
# Ensure required folders exists
#
- name: Create required paths for fonts
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ font_path }}"
  become_user: "{{ user }}"

#
# Fira Code font (With nice ligatures for programming)
#
- stat: path={{ font_path }}/{{ fira_version }}
  become_user: "{{ user }}"
  register: firacode_files

- name: Download Fira Code archive
  get_url: url=https://github.com/tonsky/FiraCode/releases/download/1.206/{{ fira_version }}.zip dest=~/Downloads/{{ fira_version }}.zip
  become_user: "{{ user }}"
  when: firacode_files.stat.exists == False

- name: Unpack Fira Code archive
  unarchive: src=~/Downloads/{{ fira_version }}.zip dest={{ font_path }} copy=no
  become_user: "{{ user }}"
  when: firacode_files.stat.exists == False

#
# SauceCodePro Nerd Font (Source Code pro with built in icons)
#
- stat: path="{{ font_path }}/SauceCodePro/"
  become_user: "{{ user }}"
  register: saucecodepro_files

- name: Create Sauce Code Pro folder
  file:
    path: "{{ font_path }}/SauceCodePro/"
    state: directory
  when: saucecodepro_files.stat.exists == False
  become_user: "{{ user }}"

- name: Download patched Sauce Code Pro
  get_url: url="https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/SourceCodePro/Medium/complete/Sauce%20Code%20Pro%20Medium%20Nerd%20Font%20Complete%20Mono.ttf?raw=true" dest={{ font_path }}/SauceCodePro/
  become_user: "{{ user }}"
  when: saucecodepro_files.stat.exists == False

#
# Microsoft TTF Core fonts (Arial, Times New Roman etc.)
#
- stat: path=/usr/share/fonts/msttcore/
  register: msttcore

- name: Install cabextract if required
  dnf: name=cabextract state=present
  when: msttcore.stat.exists == False

- name: Install Microsoft corefonts
  dnf: name=https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm state=present
  when: msttcore.stat.exists == False

#
# Install some nice basic fonts from the repos
#
- name: Install some nice basic fonts from the repos
  dnf:
    name:
      - open-sans-fonts
      - roboto-fontface-fonts
    state: present

#
# Update font cache to enable all our new fonts.
#
- name: Update font cache
  command: fc-cache
  become_user: "{{ user }}"
  when: (firacode_files.stat.exists == False) or
        (saucecodepro_files.stat.exists == False)
