- name: Install useful command line utilities (Fedora)
  dnf: name={{ item }} state=present
  with_items:
    - tmux
    - git
    - zsh
    - curl
    - mosh
    - vim
    - emacs
    - jq
    - the_silver_searcher
    - progress
    - htop
    - inotify-tools

- include: common.yml
