- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker Community Edition Repository
    baseurl: https://download.docker.com/linux/fedora/29/$basearch/stable
    enabled: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes

- name: Install docker
  dnf: name=docker-ce state=present

- include: common.yml
