- name: Install PHP
  apt:
    state: latest
    name:
      - php-fpm
      - php-mysql
      - php-mysqli
      - php-gd
      - php-curl
      - php-mbstring
      - imagemagick
      - php-imagick
      - unzip
