- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Repository for Microsoft Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Install Visual Studio Code
  dnf: name=code state=present
