- name: Deploy nextcloud
  become: yes
  docker_compose:
    project_name: nextcloud
    definition:
      version: "2"
      services:
        db:
          image: mariadb
          command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
          restart: always
          volumes:
            - db:/var/lib/mysql
          networks:
            - nextcloud
          environment:
            - MYSQL_ROOT_PASSWORD=asndjssaoienfndndj
            - MYSQL_PASSWORD=alknasknwodnsnadk
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        redis:
          image: redis:alpine
          restart: always
          networks:
            - nextcloud
        app:
          image: nextcloud:23.0.0-apache
          restart: always
          links:
            - db
          volumes:
            - nextcloud:/var/www/html
          networks:
            - traefik-external
            - nextcloud
          environment:
            - MYSQL_HOST=db
            - REDIS_HOST=redis
          labels:
            - "traefik.backend=nextcloud-backend"
            - "traefik.docker.network=traefik-external"
            - "traefik.frontend.rule=Host:nextcloud.bitnexus.net"
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.frontend.redirect.permanent=true"
            - "traefik.frontend.redirect.regex=https?://(.*)/.well-known/(card|cal)dav"
            - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
            - "traefik.frontend.headers.STSSeconds=31536000"
            - "traefik.frontend.headers.STSIncludeSubdomains=true"
        cron:
          image: nextcloud:23.0.0-apache
          restart: always
          volumes:
            - nextcloud:/var/www/html
          networks:
            - nextcloud
          entrypoint: /cron.sh
          depends_on:
            - db
            - redis
      networks:
        nextcloud:
        traefik-external:
          external: yes
      volumes:
        db:
        nextcloud:
