- name: Install useful command line utilities (Ubuntu)
  apt: name={{ item }} state=present
  with_items:
    - tmux
    - git
    - zsh
    - curl
    - mosh
    - vim
    - emacs
    - jq
    - silversearcher-ag
    - progress
    - htop

- include: common.yml
